import 'dart:convert';
import 'package:crypto/crypto.dart';

class UsernameService {
  // Funny adjectives with Indian touch
  static const List<String> funnyAdjectives = [
    'Silly',
    'Goofy',
    'Wacky',
    'Zany',
    'Bonkers',
    'Quirky',
    'Loopy',
    'Kooky',
    'Peppy',
    'Zippy',
    'Snappy',
    'Bouncy',
    'Sassy',
    'Cheeky',
    'Chubby',
    'Clumsy',
    'Tipsy',
    'Dizzy',
    'Frizzy',
    'Grimy',
    'Scruffy',
    'Nerdy',
    'Dorky',
    'Awkward',
    'Snarky',
    'Naughty',
    'Lumpy',
    'Bumpy',
    'Crusty',
    'Dusty',
    'Musty',
    'Rusty',
    'Bushy',
    'Cushy',
    'Pushy',
    'Messy',
    'Fussy',
    'Bossy',
    'Moody',
    'Glossy',
    'Squishy',
    'Swishy',
    'Wishy',
    'Fishy',
    'Gossipy',
    'Snobby',
    'Wobbly',
    'Jiggly',
    'Wiggly',
    'Cuddly',
    'Muddy',
    'Shady',
    'Grumpy',
    'Frumpy',
    'Stumpy',
    'Jumpy',
    'Crabby',
    'Grabby',
    'Shabby',
    'Flabby',
    'Jabby',
    'Webby',
    'Knotty',
    'Dotty',
    'Potty',
    'Spotty',
    'Batty',
    'Catty',
    'Fatty',
    'Ratty',
    'Chatty',
    'Bratty',
    'Gritty',
    'Witty',
    'Pitty',
    'Dilly',
    'Giddy',
    'Kiddy',
    'Weddy',
    'Teddy',
    'Heady',
    'Weedy',
    'Needy',
    'Greedy',
    'Speedy',
    'Reedy',
    'Seedy',
    'Leady',
    'Baldy',
    'Waldy',
    'Moldy',
    'Boldy',
    'Coldy',
    'Barely',
    'Fairly',
    'Rarely',
    'Purely',
    'Sorely',
    'Merely',
    'Lazily',
    'Dazily',
    'Frizzy',
    'Whizzy',
    'Fizzily',
    'Dizzy',
    'Buzzy',
    'Fuzzy',
    'Muzzy',
    'Tizzy',
    'Jazzy',
    'Razzly',
    'Snobby',
    'Hobby',
    'Lobby',
    'Shabby',
    'Tabby',
    'Gabby',
    'Cabby',
    'Slacky',
    'Tacky',
    'Wacky',
    'Zappy',
    'Nippy',
    'Zippy',
    'Hippy',
    'Dippy',
    'Tippy',
    'Lippy',
    'Poppy',
    'Soppy',
    'Hoppy',
    'Loppy',
    'Moppy',
    'Nappy',
    'Sappy',
    'Yappy',
    'Harpy',
    'Scarpy',
    'Warpy',
    'Burly',
    'Curly',
    'Hurly',
    'Surly',
    'Burly',
    'Purly',
    'Furly',
    'Swirly',
    'Twirly',
    'Whirly',
    'Pearly',
    'Early',
    'Yearly',
    'Dearly',
    'Fairly',
    'Rarely',
    'Barely',
    'Scarcely',
    'Dreary',
    'Weary',
    'Leery',
    'Jeery',
    'Beery',
    'Cheery',
    'Gleeful',
    'Zestful',
    'Restful',
    'Spiteful',
    'Gleeful',
    'Hateful',
    'Hopeful',
    'Bashful',
    'Kashful',
    'Lashful',
    'Mashful',
    'Washful',
    'Dashy',
    'Flashy',
    'Trashy',
    'Splashy',
    'Mashy',
    'Bashy',
    'Cashy',
    'Dashy',
    'Fashy',
    'Gashy',
    'Hashy',
    'Jashy',
    'Lashy',
    'Mashy',
    'Nashy',
    'Pashy',
    'Rashy',
    'Shashy',
    'Tashy',
    'Vashy',
    'Washy',
    'Yashy',
    'Zashy',
    'Balmy',
    'Palmy',
    'Calmy',
    'Qualmy',
    'Foamy',
    'Loamy',
    'Roamy',
    'Steamy',
    'Creamy',
    'Dreamy',
    'Beamy',
    'Seamy',
    'Teamy',
    'Reamey',
    'Seamey',
    'Gleamy',
    'Leaky',
    'Creaky',
    'Freaky',
    'Sneaky',
    'Squeaky',
    'Tweaky',
    'Beaky',
    'Peaky',
    'Meaky',
    'Weaky',
    'Bleak',
    'Sleek',
    'Greek',
    'Cheek',
    'Peek',
    'Meek',
    'Seek',
    'Geek',
    'Freak',
    'Streak',
    'Squeak',
    'Speak',
    'Weak',
    'Beak',
    'Peak',
    'Leak',
    'Creak',
    'Cleak',
    'Sticky',
    'Tricky',
    'Icky',
    'Picky',
    'Dicky',
    'Micky',
    'Nicky',
    'Vicky',
    'Ricky',
    'Wicky',
    'Licky',
    'Sicky',
    'Ticky',
    'Bicky',
    'Gicky',
    'Hicky',
    'Jicky',
    'Kicky',
    'Wicket',
    'Picket',
    'Ticket',
    'Cricket',
    'Thicket',
    'Gasket',
    'Basket',
    'Casket',
    'Bucket',
    'Socket',
    'Pocket',
    'Rocket',
    'Docket',
    'Locket',
    'Nocket',
    'Cocket',
    'Jockey',
    'Hockey',
    'Phooey',
    'Hooey',
    'Gooey',
    'Chewy',
    'Dewy',
    'Lewy',
    'Bewy',
    'Stewy',
    'Screwy',
    'Shrewey',
    'Bluey',
    'Cluey',
    'Gluey',
    'Fluey',
    'Slue',
    'Minty',
    'Dinty',
    'Linty',
    'Cinty',
    'Pinty',
    'Rinty',
    'Sinty',
    'Tinty',
    'Winty',
    'Zesty',
    'Testy',
    'Pesty',
    'Resty',
    'Besty',
    'Westy',
    'Crushy',
    'Bushy',
    'Gushy',
    'Hushy',
    'Lushy',
    'Mushy',
    'Pushy',
    'Rushy',
    'Tushy',
    'Cushy',
    'Slushy',
    'Flushy',
    'Plushy',
    'Brushy',
    'Brushy',
    'Rushly',
    'Blushly',
    'Shyly',
    'Slyly',
    'Dryly',
    'Fryly',
    'Pryly',
    'Tryly',
    'Cryly',
    'Greyly',
    'Breyly',
    'Preyly',
    'Freyly',
    'Dreyly',
    'Creyly',
    'Treyly',
    'Wryly',
    'Greyly',
    'Preply',
    'Flippantly',
    'Snippily',
    'Nippily',
    'Tippily',
    'Hippily',
    'Lippily',
    'Sippily',
    'Dippily',
    'Gippily',
    'Kippily',
    'Yippily',
    'Zippily',
    'Floppily',
    'Sloppily',
    'Stoppily',
    'Choppily',
    'Hoppily',
    'Moppily',
    'Poppily',
    'Soppily',
    'Yoppily',
    'Boppily',
    'Roppily',
    'Toppily',
    'Loppily',
    'Joppily',
    'Goppily',
    'Woppily',
    'Shoppily',
    'Droppily',
    'Croppily',
    'Stoppily',
    'Flappily',
    'Slappily',
    'Snappily',
    'Trappily',
    'Wrappily',
    'Clappily',
    'Strappily',
    'Chappily',
    'Nappily',
    'Happily',
    'Sappily',
    'Tappily',
    'Yappily',
    'Zappily',
    'Rappily',
    'Gappily',
    'Lappily',
    'Mappily',
    'Pappily',
  ];

  // Funny animals with Indian touch
  static const List<String> funnyNouns = [
    'Capybara',
    'Wombat',
    'Narwhal',
    'Platypus',
    'Llama',
    'Alpaca',
    'Flamingo',
    'Opossum',
    'Armadillo',
    'Sloth',
    'Lemur',
    'Meerkat',
    'Badger',
    'Otter',
    'Quokka',
    'Penguin',
    'Porcupine',
    'Skunk',
    'Ferret',
    'Hedgehog',
    'Beaver',
    'Moose',
    'Yak',
    'Seal',
    'Koala',
    'Echidna',
    'Dugong',
    'Manatee',
    'Tapir',
    'Numbat',
    'Emu',
    'Ostrich',
    'Kiwi',
    'Puffin',
    'Owl',
    'Parrot',
    'Macaw',
    'Cockatoo',
    'Toucan',
    'Hummingbird',
    'Peacock',
    'Pheasant',
    'Crane',
    'Stork',
    'Heron',
    'Egret',
    'Pelican',
    'Albatross',
    'Tern',
    'Gull',
    'Gecko',
    'Iguana',
    'Bearded',
    'Python',
    'Cobra',
    'Viper',
    'Boa',
    'Anaconda',
    'Turtle',
    'Tortoise',
    'Frog',
    'Toad',
    'Salamander',
    'Newt',
    'Carp',
    'Catfish',
    'Piranha',
    'Angelfish',
    'Guppy',
    'Molly',
    'Betta',
    'Goldfish',
    'Koi',
    'Tilapia',
    'Cichlid',
    'Loach',
    'Pufferfish',
    'Lionfish',
    'Zebrafish',
    'Killifish',
    'Jellyfish',
    'Starfish',
    'Octopus',
    'Squid',
    'Cuttlefish',
    'Snail',
    'Slug',
    'Clam',
    'Oyster',
    'Mussel',
    'Scallop',
    'Shrimp',
    'Lobster',
    'Crab',
    'Crawfish',
    'Krill',
    'Centipede',
    'Scorpion',
    'Spider',
    'Ant',
    'Bee',
    'Wasp',
    'Hornet',
    'Moth',
    'Butterfly',
    'Dragonfly',
    'Damselfly',
    'Grasshopper',
    'Cricket',
    'Katydid',
    'Cockroach',
    'Termite',
    'Earwig',
    'Beetle',
    'Ladybug',
    'Firefly',
    'Weevil',
    'Scarab',
    'Fly',
    'Mosquito',
    'Gnat',
    'Midge',
    'Aphid',
    'Thrips',
    'Macaque',
    'Baboon',
    'Gibbon',
    'Orangutan',
    'Chimpanzee',
    'Gorilla',
    'Bonobo',
    'Loris',
    'Galago',
    'Tarsier',
    'Shrew',
    'Mole',
    'Desman',
    'Weasel',
    'Stoat',
    'Ermine',
    'Mink',
    'Tayra',
    'Grison',
    'Wolverine',
    'Mongoose',
    'Suricate',
    'Fossa',
    'Hyena',
    'Aardwolf',
    'Aardvark',
    'Pangolin',
    'Felid',
    'Canid',
    'Ursid',
    'Mustelid',
    'Equid',
    'Rhinoceros',
    'Hippopotamus',
    'Whale',
    'Dolphin',
    'Porpoise',
    'Seal',
    'Walrus',
    'Manatee',
    'Dugong',
    'Bovine',
    'Caprine',
    'Cervid',
    'Suidae',
    'Camelid',
    'Giraffe',
    'Gazelle',
    'Antelope',
    'Impala',
    'Wildebeest',
    'Buffalo',
    'Musk Ox',
    'Sheep',
    'Goat',
    'Deer',
    'Elk',
    'Moose',
    'Caribou',
    'Reindeer',
    'Hyrax',
    'Elephant',
    'Afrcan',
    'Asian',
    'Tapir',
    'Horse',
    'Zebra',
    'Donkey',
    'Mule',
    'Panda',
    'Koala',
    'Tiger',
    'Lion',
    'Leopard',
    'Cheetah',
    'Cougar',
    'Jaguar',
    'Lynx',
    'Bobcat',
    'Serval',
    'Caracal',
    'Ocelot',
    'Margay',
    'Puma',
    'Cougar',
    'Panther',
    'Blackbuck',
    'Sambar',
    'Hog',
    'Monitor',
    'Dugong',
    'Gaur',
    'Banteng',
    'Bison',
    'Gayal',
    'Yak',
    'Nilgai',
    'Four Horned',
    'Cheetal',
    'Chinkara',
    'Sambhar',
    'Samba',
    'Rusa',
    'Sika',
    'Fallow',
    'Musk',
    'Hog Deer',
    'Water Deer',
    'Swamp Deer',
    'Sambar',
    'Rusa',
    'Sika',
    'Fallow Deer',
    'Red Deer',
    'Mouse Deer',
    'Dik Dik',
    'Peacock',
    'Peahen',
    'Jungle',
    'Tragopan',
    'Pheasant',
    'Quail',
    'Bustard',
    'Hornbill',
    'Kingfisher',
    'Hoopoe',
    'Roller',
    'Bee eater',
    'Sunbird',
    'Flowerpecker',
    'White Eye',
    'Bulbul',
    'Drongo',
    'Flycatcher',
    'Redstart',
    'Robin',
    'Thrush',
    'Shrike',
    'Babbler',
    'Wren',
    'Pigeon',
    'Dove',
    'Koel',
    'Cuckoo',
    'Owl',
    'Eagle',
    'Vulture',
    'Kite',
    'Hawk',
    'Falcon',
    'Kestrel',
    'Harrier',
    'Serpent',
    'Fish Eagle',
    'Stork',
    'Crane',
    'Heron',
    'Egret',
    'Night',
    'Ibis',
    'Spoonbill',
    'Flamingo',
    'Pelican',
    'Cormorant',
    'Darter',
    'Grebe',
    'Duck',
    'Goose',
    'Swan',
    'Teal',
    'Pintail',
    'Wigeon',
    'Shoveler',
    'Pochard',
    'Tufted',
    'Common Scoter',
    'Coot',
    'Moorhen',
    'Jacana',
    'Lapwing',
    'Plover',
    'Sandpiper',
    'Snipe',
    'Woodcock',
    'Curlew',
    'Redshank',
    'Godwit',
    'Greenshank',
    'Ruff',
    'Stint',
    'Phalarope',
    'Tern',
    'Gull',
    'Skua',
    'Auk',
    'Cormorant',
    'Gannet',
    'Booby',
    'Frigatebird',
    'Tropicbird',
    'Petrel',
    'Shearwater',
    'Albatross',
    'Diver',
    'Grebe',
    'Swan',
    'Goose',
    'Duck',
    'Grouse',
    'Pheasant',
    'Quail',
    'Francolin',
    'Partridge',
    'Junglefowl',
    'Turkey',
    'Peacock',
    'Pigeon',
    'Dove',
    'Parakeet',
    'Parrot',
    'Macaw',
    'Cockatoo',
    'Lory',
    'Budgerigar',
    'Finch',
    'Canary',
    'Sparrow',
    'Starling',
    'Myna',
    'Crow',
    'Raven',
    'Jay',
    'Magpie',
    'Treepie',
    'Chough',
    'Nutcracker',
    'Wagtail',
    'Pipit',
    'Lark',
    'Swift',
    'Swallow',
    'Martin',
    'Nightjar',
    'Kingfisher',
    'Bee eater',
    'Roller',
    'Hoopoe',
    'Hornbill',
    'Barbet',
    'Woodpecker',
    'Cuckoo',
    'Coel',
    'Malkoha',
    'Owlet',
    'Eagle Owl',
    'Scops Owl',
    'Barn Owl',
    'Grass Owl',
    'Bay Owl',
    'Frogmouth',
    'Potoo',
    'Oilbird',
    'Nightjar',
    'Nighthawk',
    'Whip poor Will',
    'Chuck will widow',
    'Poorwill',
    'Owlet nightjar',
    'Kakapo',
    'Kea',
    'Kiwi',
    'Cassowary',
    'Emu',
    'Ostrich',
    'Rhea',
    'Nandu',
    'Tinamon',
    'Grebe',
    'Loon',
    'Petrel',
    'Albatross',
    'Frigatebird',
    'Pelican',
    'Cormorant',
    'Anhinga',
    'Booby',
    'Gannet',
    'Tropicbird',
    'Heron',
    'Egret',
    'Bittern',
    'Night Heron',
    'Boat bill',
    'Ibis',
    'Spoonbill',
    'Flamingo',
    'Stork',
    'Jabiru',
    'Shoebill',
    'Hamerkop',
    'Crane',
    'Limpkin',
    'Sungrebe',
    'Bustard',
    'Serema',
    'Cariama',
    'Railbirds',
    'Coots',
    'Jacana',
    'Painted Snipe',
    'Oystercatcher',
    'Avocet',
    'Stilt',
    'Phalarope',
    'Gull',
    'Tern',
    'Noddies',
    'Skimmer',
    'Auks',
    'Sandgrouse',
    'Pigeon',
    'Dove',
    'Dodo',
    'Solitaire',
    'Parakeet',
    'Macaw',
  ];

  /// Generate a deterministic funny username based on UID (max 15 letters, no spaces)
  static String generateUsernameFromUid(String uid) {
    final bytes = utf8.encode(uid);
    final digest = md5.convert(bytes);
    final hashValue = digest.toString();

    final hash1 = BigInt.parse(hashValue.substring(0, 8), radix: 16);
    final hash2 = BigInt.parse(hashValue.substring(8, 16), radix: 16);
    final hash3 = BigInt.parse(hashValue.substring(16, 24), radix: 16);

    final adjIndex = hash1.toInt() % funnyAdjectives.length;
    final nounIndex = hash2.toInt() % funnyNouns.length;
    final styleChoice = hash3.toInt() % 3;

    String username = '';

    switch (styleChoice) {
      case 0:
        username = '${funnyAdjectives[adjIndex]}${funnyNouns[nounIndex]}';
        break;
      case 1:
        final num = (hash3.toInt() % 99) + 1;
        username = '${funnyAdjectives[adjIndex]}${funnyNouns[nounIndex]}$num';
        break;
      default:
        final shortAdj = funnyAdjectives[adjIndex].substring(
          0,
          min(3, funnyAdjectives[adjIndex].length),
        );
        final shortNoun = funnyNouns[nounIndex].substring(
          0,
          min(5, funnyNouns[nounIndex].length),
        );
        username = '${_capitalize(shortAdj)}${_capitalize(shortNoun)}';
    }

    return username.length > 15 ? username.substring(0, 15) : username;
  }

  /// Generate a random funny username (max 15 letters, no spaces)
  static String generateRandomUsername() {
    final random = DateTime.now().millisecondsSinceEpoch;
    final style = random % 3;

    String username = '';

    switch (style) {
      case 0:
        final adjIdx = random.toInt() % funnyAdjectives.length;
        final nounIdx =
            (random ~/ funnyAdjectives.length).toInt() % funnyNouns.length;
        username = '${funnyAdjectives[adjIdx]}${funnyNouns[nounIdx]}';
        break;
      case 1:
        final adjIdx = random.toInt() % funnyAdjectives.length;
        final nounIdx =
            (random ~/ funnyAdjectives.length).toInt() % funnyNouns.length;
        final num = (random % 99).toInt() + 1;
        username = '${funnyAdjectives[adjIdx]}${funnyNouns[nounIdx]}$num';
        break;
      default:
        final adjIdx = random.toInt() % funnyAdjectives.length;
        final nounIdx =
            (random ~/ funnyAdjectives.length).toInt() % funnyNouns.length;
        final shortAdj = funnyAdjectives[adjIdx].substring(
          0,
          min(3, funnyAdjectives[adjIdx].length),
        );
        final shortNoun = funnyNouns[nounIdx].substring(
          0,
          min(5, funnyNouns[nounIdx].length),
        );
        username = '${_capitalize(shortAdj)}${_capitalize(shortNoun)}';
    }

    return username.length > 15 ? username.substring(0, 15) : username;
  }

  /// Generate multiple random funny usernames
  static List<String> generateRandomUsernameVariations(int count) {
    return List.generate(count, (_) => generateRandomUsername());
  }

  /// Helper function to get minimum of two integers
  static int min(int a, int b) => a < b ? a : b;

  /// Helper function to capitalize a string (PascalCase each letter)
  static String _capitalize(String text) {
    if (text.isEmpty) return text;
    return text[0].toUpperCase() + text.substring(1).toLowerCase();
  }
}
